export const pricingPlans = [
  {
    id: 'personal_free',
    accountType: 'personal_free',
    badge: 'Personal',
    icon: '👥',
    title: 'Personal Free',
    price: '$0',
    cadence: '/month',
    option: 'Free',
    description: 'For families and community members who need basic missing-person alert tools.',
    features: [
      '1 missing person alert per month',
      'Community report access',
      'Basic alert sharing',
      'Public profile',
      'Upgrade anytime',
    ],
  },
  {
    id: 'personal_pro_monthly',
    accountType: 'personal_pro',
    badge: 'Personal Pro',
    icon: '⭐',
    title: 'Personal Pro',
    price: 'Paid',
    cadence: 'monthly',
    option: 'Monthly',
    recommended: true,
    description: 'Expanded personal tools for families that need more alert capacity and visibility.',
    features: [
      'More missing person alerts',
      'Priority support',
      'Boosted visibility option',
      'More image uploads',
      'Alert analytics',
      'Family contact tools',
    ],
  },
  {
    id: 'personal_pro_annual',
    accountType: 'personal_pro',
    badge: 'Personal Pro',
    icon: '🌟',
    title: 'Personal Pro Annual',
    price: 'Paid',
    cadence: 'annual',
    option: 'Annual',
    description: 'Annual personal access with the same Pro tools and future yearly savings.',
    features: [
      'Annual Pro access',
      'More missing person alerts',
      'Priority support',
      'Boosted visibility option',
      'More image uploads',
      'Family contact tools',
    ],
  },
  {
    id: 'business_starter',
    accountType: 'business',
    badge: 'Business',
    icon: '🏪',
    title: 'Business Starter',
    price: 'Paid',
    cadence: 'monthly',
    option: 'Starter',
    description: 'For local businesses that want simple sponsored promotions and safety visibility.',
    features: [
      'Business profile',
      'Create ads/promotions',
      'Image/banner ads',
      'CTA buttons',
      'Parish targeting',
      'Basic campaign stats',
    ],
  },
  {
    id: 'business_pro',
    accountType: 'business',
    badge: 'Business Pro',
    icon: '📣',
    title: 'Business Pro',
    price: 'Paid',
    cadence: 'monthly',
    option: 'Pro',
    recommended: true,
    description: 'Advanced promotional tools for businesses that need more visibility and analytics.',
    features: [
      'More ads',
      'Featured placements',
      'Discount campaigns',
      'Website/call traffic tools',
      'Priority review',
      'Advanced analytics',
    ],
  },
  {
    id: 'agency_monthly',
    accountType: 'agency',
    badge: 'Police / Agency',
    icon: '🚓',
    title: 'Police / Agency Monthly',
    price: 'Paid',
    cadence: 'monthly license',
    option: 'Monthly',
    description: 'Licensed monthly access for official public safety teams and departments.',
    features: [
      'Agency dashboard',
      'Department management',
      'Report verification',
      'Public safety notices',
      'Emergency broadcast tools',
      'Officer/staff panel',
    ],
  },
  {
    id: 'agency_annual',
    accountType: 'agency',
    badge: 'Police / Agency',
    icon: '🛡️',
    title: 'Police / Agency Annual',
    price: 'Paid',
    cadence: 'annual license',
    option: 'Annual',
    recommended: true,
    description: 'Annual agency licensing with advanced reporting and priority support.',
    features: [
      'Discounted yearly price',
      'All agency features',
      'Priority support',
      'Multi-department tools',
      'Advanced reporting',
      'Annual license management',
    ],
  },
];

export function getPlansForAccountType(accountType) {
  return pricingPlans.filter((plan) => plan.accountType === accountType);
}

export function getDefaultPlanForAccountType(accountType) {
  return getPlansForAccountType(accountType)[0] || pricingPlans[0];
}

export function getPlanById(planId) {
  return pricingPlans.find((plan) => plan.id === planId) || pricingPlans[0];
}